// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3CZNK_7cwU1PzWKyWw0CC6iqPwN-irvk',
    appId: '1:671368459509:web:e15b1be9461ab46a8d41bc',
    messagingSenderId: '671368459509',
    projectId: 'fir-demo-27ddc',
    authDomain: 'fir-demo-27ddc.firebaseapp.com',
    storageBucket: 'fir-demo-27ddc.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYT16IhdZvKPooYLPFRODoJVbUv5RaER8',
    appId: '1:671368459509:ios:4b236354af8ac0618d41bc',
    messagingSenderId: '671368459509',
    projectId: 'fir-demo-27ddc',
    storageBucket: 'fir-demo-27ddc.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3CZNK_7cwU1PzWKyWw0CC6iqPwN-irvk',
    appId: '1:671368459509:web:39c7bcd607681c698d41bc',
    messagingSenderId: '671368459509',
    projectId: 'fir-demo-27ddc',
    authDomain: 'fir-demo-27ddc.firebaseapp.com',
    storageBucket: 'fir-demo-27ddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYT16IhdZvKPooYLPFRODoJVbUv5RaER8',
    appId: '1:671368459509:ios:4b236354af8ac0618d41bc',
    messagingSenderId: '671368459509',
    projectId: 'fir-demo-27ddc',
    storageBucket: 'fir-demo-27ddc.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB24jKy56lZbD3EmrZO-9O94kfHO6Estic',
    appId: '1:671368459509:android:0edfcf229054cdab8d41bc',
    messagingSenderId: '671368459509',
    projectId: 'fir-demo-27ddc',
    storageBucket: 'fir-demo-27ddc.firebasestorage.app',
  );

}